### ISSUE TITLE
Encoding issue when uploading build info

### ISSUE THREAD

**Issue by jochenberger** [JFrogDev/build-info#48] opened 2015-05-11 08:23 UTC
```
org.codehaus.jackson.JsonParseException: Invalid UTF-8 middle byte 0x6e
 at [Source: org.apache.http.conn.EofSensorInputStream@2a791bf9; line: 3, column: 30]
	at org.codehaus.jackson.JsonParser._constructError(JsonParser.java:943)
	at org.codehaus.jackson.impl.JsonParserBase._reportError(JsonParserBase.java:632)
	at org.codehaus.jackson.impl.Utf8StreamParser._reportInvalidOther(Utf8StreamParser.java:1673)
	at org.codehaus.jackson.impl.Utf8StreamParser._reportInvalidOther(Utf8StreamParser.java:1680)
	at org.codehaus.jackson.impl.Utf8StreamParser._decodeUtf8_4(Utf8StreamParser.java:1526)
	at org.codehaus.jackson.impl.Utf8StreamParser._finishString(Utf8StreamParser.java:970)
	at org.codehaus.jackson.impl.JsonParserBase.getText(JsonParserBase.java:364)
	at org.codehaus.jackson.map.deser.StdDeserializer$StringDeserializer.deserialize(StdDeserializer.java:411)
	at org.codehaus.jackson.map.deser.StdDeserializer$StringDeserializer.deserialize(StdDeserializer.java:399)
	at org.codehaus.jackson.map.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:135)
	at org.codehaus.jackson.map.deser.SettableBeanProperty$MethodProperty.deserializeAndSet(SettableBeanProperty.java:221)
	at org.codehaus.jackson.map.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:390)
	at org.codehaus.jackson.map.deser.BeanDeserializer.deserialize(BeanDeserializer.java:286)
	at org.codehaus.jackson.map.ObjectMapper._readValue(ObjectMapper.java:1568)
	at org.codehaus.jackson.map.ObjectMapper.readValue(ObjectMapper.java:711)
	at org.codehaus.jackson.JsonParser.readValueAs(JsonParser.java:879)
	at org.jfrog.build.client.ArtifactoryHttpClient.execute(ArtifactoryHttpClient.java:202)
	at org.jfrog.build.client.ArtifactoryHttpClient.upload(ArtifactoryHttpClient.java:189)
	at org.jfrog.build.extractor.clientConfiguration.client.ArtifactoryBuildInfoClient.uploadFile(ArtifactoryBuildInfoClient.java:619)
	at org.jfrog.build.extractor.clientConfiguration.client.ArtifactoryBuildInfoClient.deployArtifact(ArtifactoryBuildInfoClient.java:330)
	at org.jfrog.gradle.plugin.artifactory.task.BuildInfoBaseTask.deployArtifacts(BuildInfoBaseTask.java:409)
	at org.jfrog.gradle.plugin.artifactory.task.BuildInfoBaseTask.prepareAndDeploy(BuildInfoBaseTask.java:284)
	at org.jfrog.gradle.plugin.artifactory.task.BuildInfoBaseTask.collectProjectBuildInfo(BuildInfoBaseTask.java:363)
```
My artifact name contains a German umlaut (ö). The upload seems to work fine but the response from artifactory cannot be parsed. There's probably a charset property missing somewhere.

**Comment by eyalbe4** [comment] 2015-05-14 04:49
@jochenberger , 
Thanks for reporting this issue!
The issue caused by a bug in org.codehaus.jackson.JsonParser the build-info client is using to parse the json response of Artifactory:
http://jira.codehaus.org/browse/ACT-1960
The bug was not yet fixed, but I still tried upgrading to the latest release of the parser, but the issue is still reproduced with it.
The build-info client needs this response to create the ArtifactoryUploadResponse object used to retrieve information about the upload. You can see the code here:
https://github.com/JFrogDev/build-info/blob/master/build-info-client/src/main/java/org/jfrog/build/client/ArtifactoryHttpClient.java
So it looks like there isn't much we can do but hope this bug is fixed soon.

**Comment by jochenberger** [comment] 2015-05-15 07:16
Are you sure that it's not just an issue of not using the correct charset to read the InputStream? Remember the default charset for HTTP 1.1 is ISO-8859-1. I don't see any charset related code in `ArtifactoryHttpClient.java`.

**Comment by eyalbe4** [comment] 2015-05-17 08:00
@jochenberger - Good news.
We can fix this issue by using the JsonFactory.createJsonParser prototype that accepts String instead of InputStream.
We opened the following Jira issue that you can follow (the fix is already committed and will be included in the next release):
https://www.jfrog.com/jira/browse/BI-200
Thanks again for reporting this issue and helping us improve!

**Closed** 2015-05-26 04:55 UTC
