### ISSUE TITLE
gradle plugin 4.4.1 breaks compatibility

### ISSUE THREAD

**Issue by ItamarBenjamin** [JFrogDev/build-info#87] opened 2016-07-11 10:03 UTC
i got an exception from gradle while building:
Task with name 'artifactoryPublish' not found in project ':api'

**Comment by ForNeVeR** [comment] 2016-07-11 10:24
For some reason my projects also were unable to build after updating 4.4.0 -> 4.4.1. Still investigating.

**Comment by eyalbe4** [comment] 2016-07-11 10:26
@ItamarBenjamin,
Does the same project build properly with an older version of the plugin? If so, what is the older version?
Since the example projects (referenced from the plugin documentation) are working with 4.4.1, can you please provide us with a sample project that reproduces this issue?

**Comment by ItamarBenjamin** [comment] 2016-07-11 11:03
yes, when i explicltly reverted to 4.4.0 everything worked well as before. (previously i had imported the plugin with version 4.+)

i will try to reproduce this situation on a sample project, our gradle setup is quite complex to copy it here

**Comment by eyalbe4** [comment] 2016-07-11 12:51
Thank you @ItamarBenjamin and @ForNeVeR.
We'll be waiting for s sample project that reproduces the issue.

**Comment by ItamarBenjamin** [comment] 2016-07-11 14:39
I have been able to reproduce this issue in a sample project

you can see the output here:
ibinyami@itstl087 /tmp/art_gradle >gradle build
[buildinfo] Not using buildInfo properties file for this build.
:compileJava UP-TO-DATE
:processResources UP-TO-DATE
:classes UP-TO-DATE
:jar
:assemble
:compileTestJava UP-TO-DATE
:processTestResources UP-TO-DATE
:testClasses UP-TO-DATE
:test UP-TO-DATE
:check UP-TO-DATE
:build

BUILD SUCCESSFUL

Total time: 5.786 secs

This build could be faster, please consider using the Gradle Daemon: https://docs.gradle.org/2.14/userguide/gradle_daemon.html

ibinyami@itstl087 /tmp/art_gradle >vi build.gradle

********* here i change the plugin version to latest **********

ibinyami@itstl087 /tmp/art_gradle >gradle build
[buildinfo] Not using buildInfo properties file for this build.

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':api'.
> Task with name 'artifactoryPublish' not found in project ':api'.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 5.591 secs
[build.gradle.txt](https://github.com/JFrogDev/build-info/files/357315/build.gradle.txt)
[settings.gradle.txt](https://github.com/JFrogDev/build-info/files/357322/settings.gradle.txt)

**Comment by ForNeVeR** [comment] 2016-07-11 15:19
I have a similar setup, but in my case it silently fails telling that it cannot find the artifacts from my artifactory repo (and listing any sorts of URLs except my actual Artifactory repo).

I have a config like this:

```groovy
artifactory {
	contextUrl = 'https://[REDACTED]/artifactory'
	resolve {
		repository {
			repoKey = 'medical-develop'
			username = "${artifactory_user}"
			password = "${artifactory_password}"
			maven = true
		}
	}
}
```

I've compared the debug logs (obtained with `./gradlew -debug build`) from 4.4.0 and 4.4.1 and I see the following difference. 4.4.0 have this line, while 4.4.1 haven't:

```
[org.jfrog.gradle.plugin.artifactory.extractor.listener.ProjectsEvaluatedBuildListener] Artifactory URL: https://[REDACTED]/artifactory/[REDACTED]
```

All the configuration files in my environment are the same.

I'll try to play with the sample projects to get the repro.

**Comment by eyalbe4** [comment] 2016-07-11 16:46
Thanks @ItamarBenjamin and @ForNeVeR,
In order to pinpoint the root cause of these failures, it would really help if you could provide us with a sample project that we can run and reproduce a failure. Since all project examples (referenced from the plugin documentation) work properly, there's obviously something in your build scripts that the new version does not support. Any chance you can try and create such a sample?

**Comment by ItamarBenjamin** [comment] 2016-07-11 17:15
@eyalbe4 Hi Eyal, I've uploaded two gradle files with my last comment, they contain the sample for the output I posted before in that comment.

**Comment by ezraroi** [comment] 2016-07-11 18:06
@ItamarBenjamin lets create a public repo tomorrow in GitHub with the sample project.
@eyalbe4 , do you have any release notes or something similar for the new version?

**Comment by eyalbe4** [comment] 2016-07-11 20:31
Sure @ezraroi,
The release notes for 4.4.1 are available [here](https://bintray.com/jfrog/jfrog-jars/build-info-extractor-gradle/4.4.1#release).
You can see the 2 commits for the 2 issues for this release. I suspect that one of them caused the issue you're experiencing. I'm sure that we'll be able to pinpoint the problem and fix it using a sample project.
All - thanks for the great cooperation!

**Comment by eyalbe4** [comment] 2016-07-12 09:37
@ezraroi, @ItamarBenjamin and @ForNeVeR, 
@ItamarBenjamin's sample indeed reproduces the issue. The build fails with:
*Task with name 'artifactoryPublish' not found in project ':api'.*
and if you apply the *com.jfrog.artifactory* plugin to the *api* subproject the issue is resolved. Before 4.4.1, the *com.jfrog.artifactory* plugin was applied automatically to all sub-projects, even if you apply it only to the root project. Since 4.4.1, you have to implicitly apply it to the relevant sub-projects. You can use of course the *allprojects* or *subprojects* closure for that.
This behaviour was changed in 4.4.1, in order to support gradle's configuration-on-demand feature, which should reduce the build time in some cases by evaluating only the relevant modules. Applying the Artifactory plugin to all sub-projects automatically triggered all sub-projects evaluation, thus overriding the on-demand evaluation. We apologise for causing this break and would appreciate your feedback.      
Please let us know if you're able to resolve the issue by applying the plugin to the relevant projects

**Comment by ForNeVeR** [comment] 2016-07-12 09:45
I think that my case is different. I'll try to make a repro sample and post another issue ASAP.

**Comment by ItamarBenjamin** [comment] 2016-07-12 09:53
Hi @eyalbe4 
Indeed it may solve the issue, but what if the api subproject should not publish anything? if what you proposed is the solution then in that case applying the plugin to the root project forces us to apply it to all sub projects and in most cases the majority of them will not need to publish anything.

Seems like the issue is that the new version of the plugin for some reason depends on the existence of the artifactoryPublish task in all subprojects.

**Comment by eyalbe4** [comment] 2016-07-12 15:19
Thanks for the feedback @ItamarBenjamin.
We created a snapshot version that resolves the issue your sample build script reproduces. [GAP-260](https://www.jfrog.com/jira/browse/GAP-260) tracks this fix.
Can please try out the snapshot version? You can install it as follows:
```
buildscript {
    repositories {
        maven {
            url "https://oss.jfrog.org/oss-snapshot-local"
        }
        jcenter()
    }
    dependencies {
        classpath "org.jfrog.buildinfo:build-info-extractor-gradle:4.4.x-SNAPSHOT"
    }
}
```

**Comment by ItamarBenjamin** [comment] 2016-07-12 18:55
Hi @eyalbe4 
I can confirm this release fixes the issue. Thank you for the quick resultion. I have ran the our build scripts and they didn't fail on configuration phase. However, I wasn't able to publish to artifactory successfully as the build now fails with this error: 

* What went wrong:
Execution failed for task ':client:artifactoryPublish'.
> File '/workarea/ibinyami/workspace/weed/java/client/build/publications/dist/pom-default.xml' does not exist, and need to be published from publication dist

**Comment by eyalbe4** [comment] 2016-07-12 19:20
@ItamarBenjamin,
We'd like to better understand the structure of your gradle project, so that we can determine why it is not compatible with the recent changes. Can you please send an email to support@jfrog.com so that we can look into this together?

**Comment by eyalbe4** [comment] 2016-07-18 13:47
@ItamarBenjamin, @ForNeVeR and @ezraroi,
I believe we have a fix for the issues discussed here, and we'd like to ask you try out the fix before publishing a new release. You can install the snapshot plugin as follows:
```
buildscript {
    repositories {
        maven {
            url "https://oss.jfrog.org/oss-snapshot-local"
        }
        jcenter()
    }
    dependencies {
        classpath "org.jfrog.buildinfo:build-info-extractor-gradle:4.4.x-SNAPSHOT"
    }
}
```

**Comment by ForNeVeR** [comment] 2016-07-18 14:41
Wow, it really seems that my problem was fixed by the patch. Thank you, guys!

**Comment by regevbr** [comment] 2016-08-07 13:00
@eyalbe4 , is it released? how can we install 4.4.2?

**Comment by eyalbe4** [comment] 2016-08-07 13:24
@regevbr, 4.4.2 will soon be published.
We'll update here as soon as it is out there.

**Comment by eyalbe4** [comment] 2016-08-08 16:02
@regevbr and all,
Version 4.4.2 is available on jcenter and should be soon available on plugins.gradle.org.

**Comment by eyalbe4** [comment] 2016-08-22 09:02
Thanks everybody. Closing this issue.

**Closed by eyalbe4** 2016-08-22 09:02 UTC

**Comment by regevbr** [comment] 2016-08-22 09:50
Thanks! 
@ItamarBenjamin
